### ISSUE TITLE
Should the .vscode directory be in the Git repository.

### ISSUE THREAD

**Issue by GrahamDumpleton** [eduk8s/eduk8s-vscode-helper#4]
Suspect that ``.vscode`` directory shouldn't be in repository. Should remove and add ``*/.vscode`` to ``.gitignore`` file.

**Comment by kdvolder** [comment]
I would keep it since it contains the 'stuff' that lets you press 'F5' and run it inside vscode debug environment. If you don't have these files it may be a bit tricky to setup for using the vscode debugger to successfully launch the extension and step it using debugger / breakpoints etc.

If you are working on the source code of the extension having the ability to launch and debug it directly in vscode is something you probably want.
